import PDFDocument from 'pdfkit';
import type { Scholarship } from '@shared/schema';
import { Readable } from 'stream';

export interface PdfTemplateOptions {
  templateVersion?: string;
  brandColor?: string;
  logoUrl?: string;
  contactEmail?: string;
}

export class PdfService {
  generateScholarshipPdf(
    scholarship: Scholarship,
    options: PdfTemplateOptions = {}
  ): { stream: Readable; filename: string } {
    const doc = new PDFDocument({
      size: 'LETTER',
      margins: { top: 50, bottom: 50, left: 50, right: 50 },
      info: {
        Title: `${scholarship.title} - Scholarship Details`,
        Author: 'ScholarMatch Platform',
        Subject: 'Scholarship Information',
        CreationDate: new Date(),
      }
    });

    const brandColor = options.brandColor || '#2563eb';
    const contactEmail = options.contactEmail || 'support@scholarmatch.app';

    doc
      .fontSize(24)
      .fillColor(brandColor)
      .text(scholarship.title, { align: 'center' })
      .moveDown(0.5);

    doc
      .fontSize(12)
      .fillColor('#6b7280')
      .text(`Scholarship ID: ${scholarship.id}`, { align: 'center' })
      .moveDown(1);

    if (scholarship.sourceOrganization) {
      doc
        .fontSize(14)
        .fillColor('#374151')
        .text(`Provided by: ${scholarship.sourceOrganization}`, { align: 'center' })
        .moveDown(1);
    }

    doc
      .fontSize(16)
      .fillColor('#111827')
      .text('Award Details', { underline: true })
      .moveDown(0.5);

    doc
      .fontSize(12)
      .fillColor('#374151')
      .text(`Amount: $${scholarship.amount.toLocaleString()}`, { continued: false })
      .text(`Deadline: ${scholarship.deadline.toLocaleDateString('en-US', { 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
      })}`)
      .text(`Level: ${scholarship.level}`)
      .moveDown(1);

    if (scholarship.major) {
      doc.text(`Major: ${scholarship.major}`).moveDown(0.5);
    }

    if (scholarship.state) {
      doc.text(`Location: ${scholarship.city ? `${scholarship.city}, ` : ''}${scholarship.state}`).moveDown(1);
    }

    doc
      .fontSize(16)
      .fillColor('#111827')
      .text('Description', { underline: true })
      .moveDown(0.5);

    doc
      .fontSize(11)
      .fillColor('#374151')
      .text(scholarship.description, { align: 'justify' })
      .moveDown(1);

    if (scholarship.requirements && typeof scholarship.requirements === 'object') {
      doc
        .fontSize(16)
        .fillColor('#111827')
        .text('Requirements', { underline: true })
        .moveDown(0.5);

      doc.fontSize(11).fillColor('#374151');
      
      const req = scholarship.requirements as Record<string, any>;
      if (req.gpa) doc.text(`• Minimum GPA: ${req.gpa}`);
      if (req.essay) doc.text(`• Essay required: Yes`);
      if (req.leadership) doc.text(`• Leadership experience required: Yes`);
      if (req.financialNeed) doc.text(`• Financial need consideration: Yes`);
      
      doc.moveDown(1);
    }

    if (scholarship.tags && scholarship.tags.length > 0) {
      doc
        .fontSize(16)
        .fillColor('#111827')
        .text('Tags', { underline: true })
        .moveDown(0.5);

      doc
        .fontSize(11)
        .fillColor('#6b7280')
        .text(scholarship.tags.join(', '))
        .moveDown(1);
    }

    if (scholarship.sourceUrl) {
      doc
        .fontSize(10)
        .fillColor('#2563eb')
        .text('Learn more:', { continued: true })
        .fillColor('#1d4ed8')
        .text(` ${scholarship.sourceUrl}`, { link: scholarship.sourceUrl })
        .moveDown(2);
    }

    doc
      .fontSize(8)
      .fillColor('#9ca3af')
      .text('━'.repeat(80), { align: 'center' })
      .moveDown(0.3)
      .text(`Generated by ScholarMatch Platform | ${new Date().toISOString()}`, { align: 'center' })
      .text(`For questions, contact: ${contactEmail}`, { align: 'center' });

    doc.end();

    const filename = `scholarship-${scholarship.id}-${Date.now()}.pdf`;

    return {
      stream: doc as unknown as Readable,
      filename
    };
  }

  async generateScholarshipPdfBuffer(
    scholarship: Scholarship,
    options: PdfTemplateOptions = {}
  ): Promise<{ buffer: Buffer; filename: string }> {
    const { stream, filename } = this.generateScholarshipPdf(scholarship, options);

    return new Promise((resolve, reject) => {
      const chunks: Buffer[] = [];

      stream.on('data', (chunk) => chunks.push(chunk));
      stream.on('end', () => resolve({ buffer: Buffer.concat(chunks), filename }));
      stream.on('error', reject);
    });
  }
}

export const pdfService = new PdfService();
